import { RarityEnum, STATS_TYPES } from '@entities/interfaces';
import { WEAPON_TYPES } from '@entities/interfaces/weapon';
import { MigrationInterface, QueryRunner } from 'typeorm';

export class migrations1730137128050 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    const values = characters
      .map(
        (char) =>
          `('${char.name}', '${char.mainStat}', '${char.statValue}', '${char.imagePath}', '${char.type}', '${char.rarity}', '${char.baseAttack}')`,
      )
      .join(', ');
    return queryRunner.query(
      `INSERT INTO "weapons" ("name", "mainStat", "statValue", "imagePath", "type", "rarity", "baseAttack")
      VALUES ${values};`,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query('DELETE FROM "characters"');
  }
}
interface Character {
  name: string;
  mainStat: STATS_TYPES;
  statValue: number;
  imagePath: string;
  type: WEAPON_TYPES;
  rarity: RarityEnum;
  baseAttack: number;
}

// 1.3 weapons
const characters: Array<Character> = [
  {
    name: 'stringmaster',
    imagePath: '/weapons/stringmaster.webp',
    baseAttack: 500,
    mainStat: STATS_TYPES.CRIT_CHANCE,
    statValue: 36,
    rarity: RarityEnum.LEGENDARY,
    type: WEAPON_TYPES.RECTIFIER,
  },
  {
    name: 'cosmicRipples',
    imagePath: '/weapons/cosmicRipples.webp',
    baseAttack: 500,
    mainStat: STATS_TYPES.ATTACK,
    statValue: 54,
    rarity: RarityEnum.LEGENDARY,
    type: WEAPON_TYPES.RECTIFIER,
  },
  {
    name: 'variation',
    imagePath: '/weapons/variation.webp',
    baseAttack: 337,
    mainStat: STATS_TYPES.ENERGY_REGENERATION,
    statValue: 51.8,
    rarity: RarityEnum.EPIC,
    type: WEAPON_TYPES.RECTIFIER,
  },
  {
    name: 'augment',
    imagePath: '/weapons/augment.webp',
    baseAttack: 412,
    mainStat: STATS_TYPES.CRIT_CHANCE,
    statValue: 20.2,
    rarity: RarityEnum.EPIC,
    type: WEAPON_TYPES.RECTIFIER,
  },
  {
    name: 'jinzhouKeeper',
    imagePath: '/weapons/jinzhouKeeper.webp',
    baseAttack: 387,
    mainStat: STATS_TYPES.ATTACK,
    statValue: 36.4,
    rarity: RarityEnum.EPIC,
    type: WEAPON_TYPES.RECTIFIER,
  },
  {
    name: 'rectifierOfVoyager',
    imagePath: '/weapons/rectifierOfVoyager.webp',
    baseAttack: 300,
    mainStat: STATS_TYPES.ENERGY_REGENERATION,
    statValue: 32.4,
    rarity: RarityEnum.COMMON,
    type: WEAPON_TYPES.RECTIFIER,
  },
  {
    name: 'guardianRectifier',
    imagePath: '/weapons/guardianRectifier.webp',
    baseAttack: 325,
    mainStat: STATS_TYPES.ATTACK,
    statValue: 24.3,
    rarity: RarityEnum.COMMON,
    type: WEAPON_TYPES.RECTIFIER,
  },
  {
    name: 'agesOfHarvest',
    imagePath: '/weapons/agesOfHarvest.png',
    baseAttack: 587,
    mainStat: STATS_TYPES.CRIT_CHANCE,
    statValue: 24.3,
    rarity: RarityEnum.LEGENDARY,
    type: WEAPON_TYPES.BROAD_BLADE,
  },
  {
    name: 'verdantSummit',
    imagePath: '/weapons/verdantSummit.webp',
    baseAttack: 588,
    mainStat: STATS_TYPES.CRIT_DAMAGE,
    statValue: 48.6,
    rarity: RarityEnum.LEGENDARY,
    type: WEAPON_TYPES.BROAD_BLADE,
  },
  {
    name: 'lustrousRazor',
    imagePath: '/weapons/lustrousRazor.webp',
    baseAttack: 588,
    mainStat: STATS_TYPES.ATTACK,
    statValue: 36.4,
    rarity: RarityEnum.LEGENDARY,
    type: WEAPON_TYPES.BROAD_BLADE,
  },
  {
    name: 'autumntrace',
    imagePath: '/weapons/autumntrace.webp',
    baseAttack: 413,
    mainStat: STATS_TYPES.CRIT_CHANCE,
    statValue: 20.3,
    rarity: RarityEnum.EPIC,
    type: WEAPON_TYPES.BROAD_BLADE,
  },
  {
    name: 'heliosCleaver',
    imagePath: '/weapons/heliosCleaver.webp',
    baseAttack: 413,
    mainStat: STATS_TYPES.ATTACK,
    statValue: 30.4,
    rarity: RarityEnum.EPIC,
    type: WEAPON_TYPES.BROAD_BLADE,
  },
  {
    name: 'broadblade41',
    imagePath: '/weapons/broadblade41.webp',
    baseAttack: 413,
    mainStat: STATS_TYPES.ENERGY_REGENERATION,
    statValue: 32.4,
    rarity: RarityEnum.EPIC,
    type: WEAPON_TYPES.BROAD_BLADE,
  },
  {
    name: 'broadbladeOfNight',
    imagePath: '/weapons/broadbladeOfNight.webp',
    baseAttack: 325,
    mainStat: STATS_TYPES.ATTACK,
    statValue: 24.3,
    rarity: RarityEnum.COMMON,
    type: WEAPON_TYPES.BROAD_BLADE,
  },
  {
    name: 'veritysHandle',
    imagePath: '/weapons/veritysHandle.webp',
    baseAttack: 588,
    mainStat: STATS_TYPES.CRIT_CHANCE,
    statValue: 24.3,
    rarity: RarityEnum.LEGENDARY,
    type: WEAPON_TYPES.GAUNTLETS,
  },
  {
    name: 'abyssSurges',
    imagePath: '/weapons/abyssSurges.webp',
    baseAttack: 587,
    mainStat: STATS_TYPES.ATTACK,
    statValue: 36.4,
    rarity: RarityEnum.LEGENDARY,
    type: WEAPON_TYPES.GAUNTLETS,
  },
  {
    name: 'stonard',
    imagePath: '/weapons/stonard.webp',
    baseAttack: 412,
    mainStat: STATS_TYPES.CRIT_CHANCE,
    statValue: 20.3,
    rarity: RarityEnum.EPIC,
    type: WEAPON_TYPES.GAUNTLETS,
  },
  {
    name: 'hollowMirage',
    imagePath: '/weapons/hollowMirage.webp',
    baseAttack: 412,
    mainStat: STATS_TYPES.ATTACK,
    statValue: 30.3,
    rarity: RarityEnum.EPIC,
    type: WEAPON_TYPES.GAUNTLETS,
  },
  {
    name: 'gauntlets21D',
    imagePath: '/weapons/gauntlets21D.webp',
    baseAttack: 387,
    mainStat: STATS_TYPES.ENERGY_REGENERATION,
    statValue: 33.8,
    rarity: RarityEnum.EPIC,
    type: WEAPON_TYPES.GAUNTLETS,
  },
  {
    name: 'gauntletsOfNight',
    imagePath: '/weapons/gauntletsOfNight.webp',
    baseAttack: 325,
    mainStat: STATS_TYPES.ATTACK,
    statValue: 24.3,
    rarity: RarityEnum.COMMON,
    type: WEAPON_TYPES.GAUNTLETS,
  },
  {
    name: 'marcato',
    imagePath: '/weapons/marcato.webp',
    baseAttack: 337,
    mainStat: STATS_TYPES.ENERGY_REGENERATION,
    statValue: 51.8,
    rarity: RarityEnum.EPIC,
    type: WEAPON_TYPES.GAUNTLETS,
  },
  {
    name: 'amityAccord',
    imagePath: '/weapons/amityAccord.webp',
    baseAttack: 337,
    mainStat: STATS_TYPES.DEFENSE,
    statValue: 61.5,
    rarity: RarityEnum.EPIC,
    type: WEAPON_TYPES.GAUNTLETS,
  },
  {
    name: 'blazingBrilliance',
    imagePath: '/weapons/blazingBrilliance.png',
    baseAttack: 587,
    mainStat: STATS_TYPES.CRIT_DAMAGE,
    statValue: 48.6,
    rarity: RarityEnum.LEGENDARY,
    type: WEAPON_TYPES.SWORD,
  },
  {
    name: 'emeraldOfGenesis',
    imagePath: '/weapons/emeraldOfGenesis.webp',
    baseAttack: 587,
    mainStat: STATS_TYPES.CRIT_CHANCE,
    statValue: 24.3,
    rarity: RarityEnum.LEGENDARY,
    type: WEAPON_TYPES.SWORD,
  },
  {
    name: 'commandoOfConviction',
    imagePath: '/weapons/commandoOfConviction.webp',
    baseAttack: 412,
    mainStat: STATS_TYPES.ATTACK,
    statValue: 30.3,
    rarity: RarityEnum.EPIC,
    type: WEAPON_TYPES.SWORD,
  },
  {
    name: 'lunarCutter',
    imagePath: '/weapons/lunarCutter.webp',
    baseAttack: 412,
    mainStat: STATS_TYPES.ATTACK,
    statValue: 30.3,
    rarity: RarityEnum.EPIC,
    type: WEAPON_TYPES.SWORD,
  },
  {
    name: 'scaleSlasher',
    imagePath: '/weapons/scaleSlasher.webp',
    baseAttack: 337,
    mainStat: STATS_TYPES.ENERGY_REGENERATION,
    statValue: 51.8,
    rarity: RarityEnum.EPIC,
    type: WEAPON_TYPES.SWORD,
  },
  {
    name: 'lumingloss',
    imagePath: '/weapons/lumingloss.webp',
    baseAttack: 387,
    mainStat: STATS_TYPES.ATTACK,
    statValue: 36.4,
    rarity: RarityEnum.EPIC,
    type: WEAPON_TYPES.SWORD,
  },
  {
    name: 'swordOfNight',
    imagePath: '/weapons/swordOfNight.webp',
    baseAttack: 325,
    mainStat: STATS_TYPES.ATTACK,
    statValue: 24.3,
    rarity: RarityEnum.COMMON,
    type: WEAPON_TYPES.SWORD,
  },
  {
    name: 'swordOfVoyager',
    imagePath: '/weapons/swordOfVoyager.webp',
    baseAttack: 325,
    mainStat: STATS_TYPES.ATTACK,
    statValue: 24.3,
    rarity: RarityEnum.COMMON,
    type: WEAPON_TYPES.SWORD,
  },
  {
    name: 'staticMist',
    imagePath: '/weapons/staticMist.webp',
    baseAttack: 588,
    mainStat: STATS_TYPES.CRIT_CHANCE,
    statValue: 24.3,
    rarity: RarityEnum.LEGENDARY,
    type: WEAPON_TYPES.PISTOLS,
  },
  {
    name: 'novaburst',
    imagePath: '/weapons/novaburst.webp',
    baseAttack: 412,
    mainStat: STATS_TYPES.ATTACK,
    statValue: 30.4,
    rarity: RarityEnum.EPIC,
    type: WEAPON_TYPES.PISTOLS,
  },
  {
    name: 'undyingFlame',
    imagePath: '/weapons/undyingFlame.webp',
    baseAttack: 412,
    mainStat: STATS_TYPES.ATTACK,
    statValue: 30.4,
    rarity: RarityEnum.EPIC,
    type: WEAPON_TYPES.PISTOLS,
  },
  {
    name: 'pistols26',
    imagePath: '/weapons/pistols26.webp',
    baseAttack: 387,
    mainStat: STATS_TYPES.ATTACK,
    statValue: 36.5,
    rarity: RarityEnum.EPIC,
    type: WEAPON_TYPES.PISTOLS,
  },
  {
    name: 'thunderbolt',
    imagePath: '/weapons/thunderbolt.webp',
    baseAttack: 387,
    mainStat: STATS_TYPES.ATTACK,
    statValue: 36.5,
    rarity: RarityEnum.EPIC,
    type: WEAPON_TYPES.PISTOLS,
  },
  {
    name: 'cadenza',
    imagePath: '/weapons/cadenza.webp',
    baseAttack: 337,
    mainStat: STATS_TYPES.ENERGY_REGENERATION,
    statValue: 51.84,
    rarity: RarityEnum.EPIC,
    type: WEAPON_TYPES.PISTOLS,
  },
  {
    name: 'pistolsOfNight',
    imagePath: '/weapons/pistolsOfNight.webp',
    baseAttack: 325,
    mainStat: STATS_TYPES.ATTACK,
    statValue: 24.3,
    rarity: RarityEnum.COMMON,
    type: WEAPON_TYPES.PISTOLS,
  },
  {
    name: 'pistolsOfVoyager',
    imagePath: '/weapons/pistolsOfVoyager.webp',
    baseAttack: 300,
    mainStat: STATS_TYPES.ATTACK,
    statValue: 30.4,
    rarity: RarityEnum.COMMON,
    type: WEAPON_TYPES.PISTOLS,
  },
];
