import type { Metadata } from 'next';
import { StylesLayout } from '@app//layouts';
import { headers } from 'next/headers';
import { DEFAULT_LANGUAGE, LOCALE_COOKIE_NAME } from '@entities/constants';
import { UserProvider } from '@app/providers';
import { getAuthorizedUser } from '@features/server/auth/getAuthorizedUser';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const lang = headers().get(LOCALE_COOKIE_NAME) || DEFAULT_LANGUAGE;
  const user = await getAuthorizedUser();
  return (
    <html lang={lang}>
      <StylesLayout>
        <UserProvider user={user}>{children}</UserProvider>
      </StylesLayout>
    </html>
  );
}
