import type { Metadata } from "next";
import { StylesLayout } from "@app//layouts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <StylesLayout>
        {children}
      </StylesLayout>
    </html>
  );
}
